<a href="https://colab.research.google.com/github/akunopaaa1-maker/Random_Sampling_Muhammad-At-Saal-Aufa-Yanuar-25090031-/blob/main/RandomSampling_Muhammad_At_Saal_Aufa_Yanuar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Import library
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from scipy import stats
import math

In [ ]:
# Upload file dataset di Google Colab
from google.colab import files
uploaded = files.upload()

Saving MovieData-2018-2020 (1).csv to MovieData-2018-2020 (1) (1).csv

In [ ]:
# Baca dataset
df = pd.read_csv(list(uploaded.keys())[0])

# Tampilkan 5 data pertama
df.head()

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
0,A Quiet Place,PG-13,Drama,2018,"April 6, 2018 (United States)",7.5,456000.0,John Krasinski,Bryan Woods,Emily Blunt,United States,17000000.0,3.503204e+08,Paramount Pictures,90.0
1,Avengers: Infinity War,PG-13,Action,2018,"April 27, 2018 (United States)",8.4,897000.0,Anthony Russo,Christopher Markus,Robert Downey Jr.,United States,321000000.0,2.048360e+09,Marvel Studios,149.0
2,Deadpool 2,R,Action,2018,"May 18, 2018 (United States)",7.7,505000.0,David Leitch,Rhett Reese,Ryan Reynolds,Canada,110000000.0,7.864705e+08,Twentieth Century Fox,119.0
3,Bohemian Rhapsody,PG-13,Biography,2018,"November 2, 2018 (United States)",7.9,476000.0,Bryan Singer,Anthony McCarten,Rami Malek,United Kingdom,52000000.0,9.119026e+08,Twentieth Century Fox,134.0
4,Black Panther,PG-13,Action,2018,"February 16, 2018 (United States)",7.3,661000.0,Ryan Coogler,Ryan Coogler,Chadwick Boseman,United States,200000000.0,1.347598e+09,Marvel Studios,134.0

In [ ]:
# Melihat nama kolom
df.columns

Index(['name', 'rating', 'genre', 'year', 'released', 'score', 'votes',
       'director', 'writer', 'star', 'country', 'budget', 'gross', 'company',
       'runtime'],
      dtype='object')

In [ ]:
# Cek jumlah data berdasarkan Genre
df['genre'].value_counts()

genre
Action       88
Comedy       45
Drama        38
Biography    29
Animation    23
Adventure    19
Horror       15
Crime        12
Fantasy       3
Thriller      1
Sci-Fi        1
Name: count, dtype: int64

In [12]:
# 1. Hitung kemunculan setiap genre
genre_counts = df['genre'].value_counts()

# 2. Ambil genre yang muncul minimal 2 kali (agar bisa dibagi ke train dan test)
valid_genres = genre_counts[genre_counts >= 2].index

# 3. Filter dataframe agar hanya menyisakan genre yang valid
df_filtered = df[df['genre'].isin(valid_genres)]

# 4. Jalankan Stratified Random Sampling menggunakan data yang sudah difilter
train_data, stratified_sample = train_test_split(
    df_filtered,
    test_size=0.2,
    stratify=df_filtered['genre'],
    random_state=31 # Sesuai dengan 3 digit terakhir NIM kamu
)

# Tampilkan hasil sampling
stratified_sample

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
150,Yesterday,PG-13,Comedy,2019,"June 28, 2019 (United States)",6.8,131000.0,Danny Boyle,Richard Curtis,Himesh Patel,United Kingdom,26000000.0,1.531934e+08,Decibel Films,116.0
131,The 15:17 to Paris,PG-13,Biography,2018,"February 9, 2018 (United States)",5.3,30000.0,Clint Eastwood,Dorothy Blyskal,Alek Skarlatos,United States,30000000.0,5.707629e+07,Warner Bros.,94.0
15,BlacKkKlansman,R,Biography,2018,"August 10, 2018 (United States)",7.5,236000.0,Spike Lee,Charlie Wachtel,John David Washington,United States,15000000.0,9.341371e+07,Focus Features,135.0
32,The Favourite,R,Biography,2018,"December 21, 2018 (United States)",7.5,181000.0,Yorgos Lanthimos,Deborah Davis,Olivia Colman,Ireland,15000000.0,9.591871e+07,Fox Searchlight Pictures,119.0
11,Venom,PG-13,Action,2018,"October 5, 2018 (United States)",6.7,387000.0,Ruben Fleischer,Jeff Pinkner,Tom Hardy,China,100000000.0,8.560852e+08,Avi Arad Productions,112.0
107,Insidious: The Last Key,PG-13,Horror,2018,"January 5, 2018 (United States)",5.7,55000.0,Adam Robitel,Leigh Whannell,Lin Shaye,United States,10000000.0,1.678856e+08,Blumhouse Productions,103.0
265,The Call of the Wild,PG,Adventure,2020,"February 21, 2020 (United States)",6.8,42000.0,Chris Sanders,Michael Green,Harrison Ford,Canada,135000000.0,1.111055e+08,20th Century Studios,100.0
191,Ad Astra,PG-13,Adventure,2019,"September 20, 2019 (United States)",6.5,208000.0,James Gray,James Gray,Brad Pitt,China,90000000.0,1.274619e+08,New Regency Productions,123.0
125,Second Act,PG-13,Comedy,2018,"December 21, 2018 (United States)",5.8,24000.0,Peter Segal,Justin Zackham,Jennifer Lopez,United States,16000000.0,7.229407e+07,Huayi Brothers,103.0
63,The Spy Who Dumped Me,R,Action,2018,"August 3, 2018 (United States)",6.1,72000.0,Susanna Fogel,Susanna Fogel,Justin Theroux,Canada,40000000.0,7.533946e+07,BRON Studios,117.0
29,Eighth Grade,R,Comedy,2018,"August 3, 2018 (United States)",7.4,68000.0,Bo Burnham,Bo Burnham,Elsie Fisher,United States,2000000.0,1.434743e+07,A24,93.0
77,Widows,R,Crime,2018,"November 16, 2018 (United States)",6.9,91000.0,Steve McQueen,Gillian Flynn,Viola Davis,United Kingdom,42000000.0,7.598470e+07,New Regency Productions,129.0
273,It's Just Us,NaN,Drama,2020,"October 1, 2020 (United States)",NaN,NaN,James Randall,James Randall,Christina Roz,United States,15000.0,NaN,NaN,120.0
68,Tomb Raider,PG-13,Action,2018,"March 16, 2018 (United States)",6.3,197000.0,Roar Uthaug,Geneva Robertson-Dworet,Alicia Vikander,United Kingdom,94000000.0,2.746508e+08,Warner Bros.,119.0
158,Jojo Rabbit,PG-13,Comedy,2019,"November 8, 2019 (United States)",7.9,328000.0,Taika Waititi,Christine Leunens,Roman Griffin Davis,New Zealand,14000000.0,9.033502e+07,TSG Entertainment,108.0
111,Johnny English Strikes Again,PG,Action,2018,"October 26, 2018 (United States)",6.2,67000.0,David Kerr,William Davies,Rowan Atkinson,United Kingdom,25000000.0,1.589725e+08,Universal Pictures,89.0
102,The House with a Clock in Its Walls,PG,Comedy,2018,"September 21, 2018 (United States)",6.1,48000.0,Eli Roth,John Bellairs,Jack Black,United States,42000000.0,1.315231e+08,DreamWorks,105.0
117,Assassination Nation,R,Action,2018,"September 21, 2018 (United States)",6.0,17000.0,Sam Levinson,Sam Levinson,Odessa Young,United States,7000000.0,2.584988e+06,BRON Studios,108.0
27,Instant Family,PG-13,Comedy,2018,"November 16, 2018 (United States)",7.3,97000.0,Sean Anders,Sean Anders,Mark Wahlberg,United States,48000000.0,1.205562e+08,Closest to the Hole Productions,118.0
5,Hereditary,R,Drama,2018,"June 8, 2018 (United States)",7.3,259000.0,Ari Aster,Ari Aster,Toni Collette,United States,10000000.0,8.023966e+07,PalmStar Media,127.0
174,Dora and the Lost City of Gold,PG,Adventure,2019,"August 9, 2019 (United States)",6.1,27000.0,James Bobin,Nicholas Stoller,Isabela Merced,United States,49000000.0,1.196826e+08,Paramount Players,102.0
21,Den of Thieves,R,Action,2018,"January 19, 2018 (United States)",7.0,99000.0,Christian Gudegast,Christian Gudegast,Gerard Butler,United States,30000000.0,8.050962e+07,STX Films,140.0
42,The Equalizer 2,R,Action,2018,"July 20, 2018 (United States)",6.7,141000.0,Antoine Fuqua,Richard Wenk,Denzel Washington,United States,62000000.0,1.904002e+08,Columbia Pictures,121.0
178,Aladdin,PG,Adventure,2019,"May 24, 2019 (United States)",6.9,239000.0,Guy Ritchie,John August,Will Smith,United Kingdom,183000000.0,1.050694e+09,Walt Disney Pictures,128.0
3,Bohemian Rhapsody,PG-13,Biography,2018,"November 2, 2018 (United States)",7.9,476000.0,Bryan Singer,Anthony McCarten,Rami Malek,United Kingdom,52000000.0,9.119026e+08,Twentieth Century Fox,134.0
56,Mary Poppins Returns,PG,Comedy,2018,"December 19, 2018 (United States)",6.7,80000.0,Rob Marshall,P.L. Travers,Emily Blunt,United States,130000000.0,3.495461e+08,Lucamar Productions,130.0
243,The Wandering Earth,TV-MA,Action,2019,"February 5, 2019 (China)",6.0,28000.0,Frant Gwo,Gong Geer,Jing Wu,China,48000000.0,6.999925e+08,Beijing Dengfeng International Culture Communi...,125.0
136,SuperFly,R,Action,2018,"June 13, 2018 (United States)",5.2,6500.0,Director X.,Alex Tse,Trevor Jackson,United States,16000000.0,2.078068e+07,Columbia Pictures,116.0
159,Shazam!,PG-13,Action,2019,"April 5, 2019 (United States)",7.0,284000.0,David F. Sandberg,Henry Gayden,Zachary Levi,United States,100000000.0,3.659717e+08,Warner Bros.,132.0
248,Poms,PG-13,Comedy,2019,"May 10, 2019 (United States)",6.0,4700.0,Zara Hayes,Zara Hayes,Diane Keaton,United Kingdom,10000000.0,1.641822e+07,Entertainment One,90.0
61,Peter Rabbit,PG,Animation,2018,"February 9, 2018 (United States)",6.6,38000.0,Will Gluck,Rob Lieber,James Corden,United States,50000000.0,3.514961e+08,Columbia Pictures,95.0
263,Sonic the Hedgehog,PG,Action,2020,"February 14, 2020 (United States)",6.5,102000.0,Jeff Fowler,Pat Casey,Ben Schwartz,United States,85000000.0,3.197157e+08,Paramount Pictures,99.0
35,Sicario: Day of the Soldado,R,Action,2018,"June 29, 2018 (United States)",7.1,132000.0,Stefano Sollima,Taylor Sheridan,Benicio Del Toro,United States,35000000.0,7.583774e+07,Columbia Pictures,122.0
54,Adrift,PG-13,Action,2018,"June 1, 2018 (United States)",6.6,50000.0,Baltasar Kormákur,Aaron Kandell,Shailene Woodley,Hong Kong,35000000.0,5.994501e+07,Huayi Brothers,96.0
41,The Nun,R,Horror,2018,"September 7, 2018 (United States)",5.3,127000.0,Corin Hardy,Gary Dauberman,Demián Bichir,United States,22000000.0,3.655517e+08,Atomic Monster,96.0
78,Searching,PG-13,Drama,2018,"August 31, 2018 (United States)",7.6,148000.0,Aneesh Chaganty,Aneesh Chaganty,John Cho,United States,880000.0,7.546204e+07,Screen Gems,102.0
123,Smallfoot,PG,Animation,2018,"September 28, 2018 (United States)",6.6,36000.0,Karey Kirkpatrick,Karey Kirkpatrick,Channing Tatum,United States,80000000.0,2.140401e+08,Warner Animation Group,96.0
259,Tenet,PG-13,Action,2020,"September 3, 2020 (United States)",7.4,387000.0,Christopher Nolan,Christopher Nolan,John David Washington,United States,205000000.0,3.636566e+08,Warner Bros.,150.0
36,Fifty Shades Freed,R,Drama,2018,"February 9, 2018 (United States)",4.5,59000.0,James Foley,Niall Leonard,Dakota Johnson,United States,55000000.0,3.719878e+08,Perfect World Pictures,105.0
166,Alita: Battle Angel,PG-13,Action,2019,"February 14, 2019 (United States)",7.3,240000.0,Robert Rodriguez,James Cameron,Rosa Salazar,United States,170000000.0,4.049805e+08,Twentieth Century Fox,122.0
245,Sunrise in Heaven,Not Rated,Drama,2019,"April 9, 2019 (United States)",6.0,871.0,Waymon Boone,Dan Benamor,Caylee Cowan,United States,1100000.0,NaN,Nasser Group,85.0
58,Vice,R,Biography,2018,"December 25, 2018 (United States)",7.2,130000.0,Adam McKay,Adam McKay,Christian Bale,United States,60000000.0,7.607349e+07,Annapurna Pictures,132.0
164,The Irishman,R,Biography,2019,"November 27, 2019 (United States)",7.8,344000.0,Martin Scorsese,Steven Zaillian,Robert De Niro,United States,159000000.0,9.688530e+05,Tribeca Productions,209.0
51,Robin Hood,PG-13,Action,2018,"November 21, 2018 (United States)",5.3,68000.0,Otto Bathurst,Ben Chandler,Taron Egerton,United States,100000000.0,8.649305e+07,Summit Entertainment,116.0
59,Hotel Transylvania 3: Summer Vacation,PG,Animation,2018,"July 13, 2018 (United States)",6.3,62000.0,Genndy Tartakovsky,Genndy Tartakovsky,Adam Sandler,United States,80000000.0,5.285838e+08,Sony Pictures Animation,97.0
220,The Lego Movie 2: The Second Part,PG,Animation,2019,"February 8, 2019 (United States)",6.6,58000.0,Mike Mitchell,Phil Lord,Chris Pratt,Denmark,99000000.0,1.923065e+08,Warner Bros.,107.0
57,Bumblebee,PG-13,Action,2018,"December 21, 2018 (United States)",6.7,147000.0,Travis Knight,Christina Hodson,Hailee Steinfeld,China,135000000.0,4.679896e+08,Hasbro,114.0
143,Midsommar,R,Drama,2019,"July 3, 2019 (United States)",7.1,232000.0,Ari Aster,Ari Aster,Florence Pugh,United States,9000000.0,4.796764e+07,A24,148.0
232,Abominable,PG,Animation,2019,"September 27, 2019 (United States)",7.0,32000.0,Jill Culton,Jill Culton,Chloe Bennet,United States,75000000.0,1.803142e+08,DreamWorks Animation,97.0
127,The Possession of Hannah Grace,R,Horror,2018,"November 30, 2018 (United States)",5.2,20000.0,Diederik Van Rooijen,Brian Sieve,Shay Mitchell,United States,7700000.0,4.301653e+07,Screen Gems,86.0
0,A Quiet Place,PG-13,Drama,2018,"April 6, 2018 (United States)",7.5,456000.0,John Krasinski,Bryan Woods,Emily Blunt,United States,17000000.0,3.503204e+08,Paramount Pictures,90.0
25,Mamma Mia! Here We Go Again,PG-13,Comedy,2018,"July 20, 2018 (United States)",6.6,85000.0,Ol Parker,Ol Parker,Lily James,United Kingdom,75000000.0,3.956182e+08,Universal Pictures,114.0
17,White Boy Rick,R,Crime,2018,"September 14, 2018 (United States)",6.5,33000.0,Yann Demange,Andy Weiss,Matthew McConaughey,United States,29000000.0,2.595748e+07,LBI Productions,111.0
253,The Sun Is also a Star,PG-13,Drama,2019,"May 17, 2019 (United States)",5.9,6600.0,Ry Russo-Young,Tracy Oliver,Yara Shahidi,United States,9000000.0,6.750029e+06,Alloy Entertainment,100.0
260,Birds of Prey,R,Action,2020,"February 7, 2020 (United States)",6.1,190000.0,Cathy Yan,Christina Hodson,Margot Robbie,United States,84500000.0,2.018585e+08,Clubhouse Pictures (II),109.0

In [13]:
# Ambil hanya 30 data teratas dari hasil sampling
sample_30 = stratified_sample.head(30)

# Tampilkan 30 data
sample_30

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
150,Yesterday,PG-13,Comedy,2019,"June 28, 2019 (United States)",6.8,131000.0,Danny Boyle,Richard Curtis,Himesh Patel,United Kingdom,26000000.0,1.531934e+08,Decibel Films,116.0
131,The 15:17 to Paris,PG-13,Biography,2018,"February 9, 2018 (United States)",5.3,30000.0,Clint Eastwood,Dorothy Blyskal,Alek Skarlatos,United States,30000000.0,5.707629e+07,Warner Bros.,94.0
15,BlacKkKlansman,R,Biography,2018,"August 10, 2018 (United States)",7.5,236000.0,Spike Lee,Charlie Wachtel,John David Washington,United States,15000000.0,9.341371e+07,Focus Features,135.0
32,The Favourite,R,Biography,2018,"December 21, 2018 (United States)",7.5,181000.0,Yorgos Lanthimos,Deborah Davis,Olivia Colman,Ireland,15000000.0,9.591871e+07,Fox Searchlight Pictures,119.0
11,Venom,PG-13,Action,2018,"October 5, 2018 (United States)",6.7,387000.0,Ruben Fleischer,Jeff Pinkner,Tom Hardy,China,100000000.0,8.560852e+08,Avi Arad Productions,112.0
107,Insidious: The Last Key,PG-13,Horror,2018,"January 5, 2018 (United States)",5.7,55000.0,Adam Robitel,Leigh Whannell,Lin Shaye,United States,10000000.0,1.678856e+08,Blumhouse Productions,103.0
265,The Call of the Wild,PG,Adventure,2020,"February 21, 2020 (United States)",6.8,42000.0,Chris Sanders,Michael Green,Harrison Ford,Canada,135000000.0,1.111055e+08,20th Century Studios,100.0
191,Ad Astra,PG-13,Adventure,2019,"September 20, 2019 (United States)",6.5,208000.0,James Gray,James Gray,Brad Pitt,China,90000000.0,1.274619e+08,New Regency Productions,123.0
125,Second Act,PG-13,Comedy,2018,"December 21, 2018 (United States)",5.8,24000.0,Peter Segal,Justin Zackham,Jennifer Lopez,United States,16000000.0,7.229407e+07,Huayi Brothers,103.0
63,The Spy Who Dumped Me,R,Action,2018,"August 3, 2018 (United States)",6.1,72000.0,Susanna Fogel,Susanna Fogel,Justin Theroux,Canada,40000000.0,7.533946e+07,BRON Studios,117.0
29,Eighth Grade,R,Comedy,2018,"August 3, 2018 (United States)",7.4,68000.0,Bo Burnham,Bo Burnham,Elsie Fisher,United States,2000000.0,1.434743e+07,A24,93.0
77,Widows,R,Crime,2018,"November 16, 2018 (United States)",6.9,91000.0,Steve McQueen,Gillian Flynn,Viola Davis,United Kingdom,42000000.0,7.598470e+07,New Regency Productions,129.0
273,It's Just Us,NaN,Drama,2020,"October 1, 2020 (United States)",NaN,NaN,James Randall,James Randall,Christina Roz,United States,15000.0,NaN,NaN,120.0
68,Tomb Raider,PG-13,Action,2018,"March 16, 2018 (United States)",6.3,197000.0,Roar Uthaug,Geneva Robertson-Dworet,Alicia Vikander,United Kingdom,94000000.0,2.746508e+08,Warner Bros.,119.0
158,Jojo Rabbit,PG-13,Comedy,2019,"November 8, 2019 (United States)",7.9,328000.0,Taika Waititi,Christine Leunens,Roman Griffin Davis,New Zealand,14000000.0,9.033502e+07,TSG Entertainment,108.0
111,Johnny English Strikes Again,PG,Action,2018,"October 26, 2018 (United States)",6.2,67000.0,David Kerr,William Davies,Rowan Atkinson,United Kingdom,25000000.0,1.589725e+08,Universal Pictures,89.0
102,The House with a Clock in Its Walls,PG,Comedy,2018,"September 21, 2018 (United States)",6.1,48000.0,Eli Roth,John Bellairs,Jack Black,United States,42000000.0,1.315231e+08,DreamWorks,105.0
117,Assassination Nation,R,Action,2018,"September 21, 2018 (United States)",6.0,17000.0,Sam Levinson,Sam Levinson,Odessa Young,United States,7000000.0,2.584988e+06,BRON Studios,108.0
27,Instant Family,PG-13,Comedy,2018,"November 16, 2018 (United States)",7.3,97000.0,Sean Anders,Sean Anders,Mark Wahlberg,United States,48000000.0,1.205562e+08,Closest to the Hole Productions,118.0
5,Hereditary,R,Drama,2018,"June 8, 2018 (United States)",7.3,259000.0,Ari Aster,Ari Aster,Toni Collette,United States,10000000.0,8.023966e+07,PalmStar Media,127.0
174,Dora and the Lost City of Gold,PG,Adventure,2019,"August 9, 2019 (United States)",6.1,27000.0,James Bobin,Nicholas Stoller,Isabela Merced,United States,49000000.0,1.196826e+08,Paramount Players,102.0
21,Den of Thieves,R,Action,2018,"January 19, 2018 (United States)",7.0,99000.0,Christian Gudegast,Christian Gudegast,Gerard Butler,United States,30000000.0,8.050962e+07,STX Films,140.0
42,The Equalizer 2,R,Action,2018,"July 20, 2018 (United States)",6.7,141000.0,Antoine Fuqua,Richard Wenk,Denzel Washington,United States,62000000.0,1.904002e+08,Columbia Pictures,121.0
178,Aladdin,PG,Adventure,2019,"May 24, 2019 (United States)",6.9,239000.0,Guy Ritchie,John August,Will Smith,United Kingdom,183000000.0,1.050694e+09,Walt Disney Pictures,128.0
3,Bohemian Rhapsody,PG-13,Biography,2018,"November 2, 2018 (United States)",7.9,476000.0,Bryan Singer,Anthony McCarten,Rami Malek,United Kingdom,52000000.0,9.119026e+08,Twentieth Century Fox,134.0
56,Mary Poppins Returns,PG,Comedy,2018,"December 19, 2018 (United States)",6.7,80000.0,Rob Marshall,P.L. Travers,Emily Blunt,United States,130000000.0,3.495461e+08,Lucamar Productions,130.0
243,The Wandering Earth,TV-MA,Action,2019,"February 5, 2019 (China)",6.0,28000.0,Frant Gwo,Gong Geer,Jing Wu,China,48000000.0,6.999925e+08,Beijing Dengfeng International Culture Communi...,125.0
136,SuperFly,R,Action,2018,"June 13, 2018 (United States)",5.2,6500.0,Director X.,Alex Tse,Trevor Jackson,United States,16000000.0,2.078068e+07,Columbia Pictures,116.0
159,Shazam!,PG-13,Action,2019,"April 5, 2019 (United States)",7.0,284000.0,David F. Sandberg,Henry Gayden,Zachary Levi,United States,100000000.0,3.659717e+08,Warner Bros.,132.0
248,Poms,PG-13,Comedy,2019,"May 10, 2019 (United States)",6.0,4700.0,Zara Hayes,Zara Hayes,Diane Keaton,United Kingdom,10000000.0,1.641822e+07,Entertainment One,90.0

In [15]:
# Cek kolom Budget
sample_30['budget'].head()

150     26000000.0
131     30000000.0
15      15000000.0
32      15000000.0
11     100000000.0
Name: budget, dtype: float64

In [17]:
# Mengubah kolom Budget menjadi angka
sample_30['budget'] = pd.to_numeric(sample_30['budget'], errors='coerce')

# Menghapus data Budget yang kosong
budget_sample = sample_30['budget'].dropna()

budget_sample

/tmp/ipykernel_6289/1180105429.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample_30['budget'] = pd.to_numeric(sample_30['budget'], errors='coerce')

150     26000000.0
131     30000000.0
15      15000000.0
32      15000000.0
11     100000000.0
107     10000000.0
265    135000000.0
191     90000000.0
125     16000000.0
63      40000000.0
29       2000000.0
77      42000000.0
273        15000.0
68      94000000.0
158     14000000.0
111     25000000.0
102     42000000.0
117      7000000.0
27      48000000.0
5       10000000.0
174     49000000.0
21      30000000.0
42      62000000.0
178    183000000.0
3       52000000.0
56     130000000.0
243     48000000.0
136     16000000.0
159    100000000.0
248     10000000.0
Name: budget, dtype: float64

In [18]:
# Menghitung jumlah data, rata-rata, dan standar deviasi
n = len(budget_sample)
mean_budget = np.mean(budget_sample)
std_budget = np.std(budget_sample, ddof=1)

print("Jumlah data:", n)
print("Rata-rata Budget:", mean_budget)
print("Standar Deviasi:", std_budget)

Jumlah data: 30
Rata-rata Budget: 48033833.333333336
Standar Deviasi: 45345237.32135366

In [19]:
# Estimasi mean populasi menggunakan T-Distribution
# Confidence level 95%

confidence_level = 0.95
alpha = 1 - confidence_level
dfree = n - 1

t_value = stats.t.ppf(1 - alpha/2, dfree)

margin_error = t_value * (std_budget / math.sqrt(n))

lower_bound = mean_budget - margin_error
upper_bound = mean_budget + margin_error

print("T Value:", t_value)
print("Margin of Error:", margin_error)
print("Estimasi Mean Budget:")
print("Lower Bound:", lower_bound)
print("Upper Bound:", upper_bound)

T Value: 2.045229642132703
Margin of Error: 16932189.88854588
Estimasi Mean Budget:
Lower Bound: 31101643.444787458
Upper Bound: 64966023.221879214

In [20]:
# Kesimpulan otomatis

print("Kesimpulan:")
print(f"Berdasarkan 30 data sampel hasil Stratified Random Sampling berdasarkan Genre,")
print(f"dengan random_state = 31 sesuai NIM, diperoleh rata-rata Budget Film sebesar {mean_budget:.2f}.")
print(f"Dengan tingkat kepercayaan 95%, estimasi rata-rata Budget Film populasi berada")
print(f"di antara {lower_bound:.2f} sampai {upper_bound:.2f}.")

Kesimpulan:
Berdasarkan 30 data sampel hasil Stratified Random Sampling berdasarkan Genre,
dengan random_state = 31 sesuai NIM, diperoleh rata-rata Budget Film sebesar 48033833.33.
Dengan tingkat kepercayaan 95%, estimasi rata-rata Budget Film populasi berada
di antara 31101643.44 sampai 64966023.22.